== Charakteraspekte
Bei der Erschaffung eines Charakters für _Fate Core_ legt der Spieler zunächst _Konzept_ und _Dilemma_ des
Charakters fest. Dies gilt auch für _Schwert & Schicksal_. Danach kannst Du noch drei weitere Aspekte
wählen.

=== Rassen
Die Rasse des Charakters in einer High-Fantasy-Welt ist durchaus wichtig und beschert dem Charakter Vorteile
sowie auch Komplikationen. Rassen werden als _Extra_ realisiert. Jedoch muss der Charakter die Rasse in seinem
_Konzept_ benennen; diese kann sich auch während des Spiels nicht ändern.

=== Nutzung von Magie
_Schwert & Schicksal_ kennt zwei Arten von Magie: arkane und göttliche. Die göttliche Magie wird einem
Charakter durch ein höheres Wesen gewährt, während die arkane Magie eine angeborene Kraft ist.
Regeltechnisch werden beide Arten in weiten Teilen gleich behandelt. Sie werden über ein _Extra_ realisiert.

Um Magie einsetzen zu können muss der Charakter über das Extra _Magie_ verfügen, was es erforderlich macht,
dass der Charakter einen Aspekt besitzt, der die Art der Magie benennt. Dabei spielt es keine Rolle, welche 
Begriffe genannt werden (wie bspw. _Magier_, _Hexenmeister_, _Schamane_, _Adept_, _Priester_, _Kleriker), 
solange alle Spieler das gleiche Verständnis davon haben, dass dieser Charakter über eine magische Fähigkeit 
verfügt.

Wenn du bereits bei der Charaktererschaffung festlegst, dass der Charakter über magische Fähigkeiten verfügt,
kannst du dies im _Konzept_ des Charakters aufnehmen (bspw. _elfischer Magier_). Wenn du dies erst später
hinzufügen möchtest (beim Erreichen eines Meilensteins), musst du einen bestehenden Aspekt entsprechend
abändern.
