== Fertigkeiten
_Schwert & Schicksal_ nutzt die vollständige Liste der _Fertigkeiten_ aus _Fate Core_. Einige der _Fertigkeiten_
werden modifiziert oder eingeschränkt. Es kommen einige wenige neue _Fertigkeiten_ hinzu.

=== Übersicht
Die folgende Tabelle gibt einen Überblick über alle _Fertigkeiten_ und welche Aktionen mit der jeweiligen
_Fertigkeit_ möglich sind.

<<<

[frame=ends, grid=rows, stripes=even, cols="<2h,4*^1"]
|===
| Fertigkeit      | [.icon]#O# | [.icon]#C# | [.icon]#A# | [.icon]#D#

| Athletik        | X | X |   | X
| Charisma        | X | X |   | X
| Diebeskunst     | X | X |   |
| Empathie        | X | X |   | X
| Handwerk        | X | X |   |
| Heimlichkeit    | X | X |   | X
| Kämpfen         | X | X | X | X
| Kontakte        | X | X |   | X
| Kraft           | X | X |   | X
| Magie *         | X | X | X | X
| Nachforschungen | X | X |   |
| Provozieren     | X | X | X |
| Reiten          | X | X | X | X
| Ressourcen *    | X | X | X | X
| Schießen        | X | X | X |
| Täuschung       | X | X |   | X
| Wahrnehmung     | X | X |   | X
| Wille           | X | X |   | X
| Wissen          | X | X |   | X
|===

NOTE: _Fertigkeiten_, hinter deren Namen ein Sternchen steht, können nur eingeschränkt erworben und
gesteigert werden. Details findest Du in der jeweiligen Beschreibung dieser _Fertigkeiten_.

=== Beschreibung der Fertigkeiten

==== Athletik
_Athletik_ wird so eingesetzt wie in den _Fate Core Grundregeln_ beschrieben.

[.icon]#O# Du kannst _Hindernisse_ mittels körperlicher Bewegung überwinden: Schwimmen, Ausweichen, Rennen, ...

[.icon]#C# Du kannst einen _Vorteil_ erschaffen, in dem Du auf eine höhere Position kletterst oder springst.

[.icon]#A# -

[.icon]#D# Du kannst _Athletik_ zur Verteidigung gegen alle Arten von Angriffen einsetzen (Nahkampf-
sowie Fernkampfangriffe).

===== Stunts
* Sprinter
* Kletterer
* Pfeile und Bolzen abwehren

==== Charisma
_Charisma_ wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt.

[.icon]#O# Du kannst andere Personen inspirieren oder überzeugen.

[.icon]#C# Du kannst andere dazu bringen, dir zu vertrauen oder dir zu folgen.

[.icon]#A# -

[.icon]#D# Du kannst dich gegen Angriffe verteidigen, die deinen Ruf schädigen.

===== Stunts
* Einen guten Eindruck machen
* Demagoge
* beliebt

==== Diebeskunst
Mit _Diebeskunst_ kannst Du Gegenstände stehlen, Spuren verwischen, Objekte am Körper verbergen, an Orte gelangen,
zu denen Dir der Zutritt eigentlich verwehrt ist und Ähnliches.

[.icon]#O# Du kannst Taschendiebstahl oder eine einfache Infiltration durchführen oder deine Spuren verwischen.
Du kannst Schlösser knacken und Fallen überwinden.

[.icon]#C# Du kannst Orte oder Personen ausspionieren und dabei Schwachstellen für einen Einbruch oder
Diebstahl aufdecken.

[.icon]#A# -

[.icon]#D# -

===== Stunts
* Meisterdieb
* Entfesslungskünstler
* Es gibt immer einen Ausweg

==== Empathie
Mit _Empathie_ kannst Du Gefühle und Regungen in Personen, Monstern und Tieren wahrnehmen.

[.icon]#O# -

[.icon]#C# Du kannst den emotionalen Zustand deines Gegenübers erkennen und darüber neue Aspekte erschaffen.

[.icon]#A# -

[.icon]#D# Du kannst Dich mit Empathie gegen Angriffe wie _Täuschung_ verteidigen und Lügen anderer durchschauen.

===== Stunts

===== Sonderregel
Du kannst _Empathie_ nutzen um anderen zu helfen, sich von geistigen Konsequenzen zu erholen.

==== Handwerk
Umfasst alle Arten von Arbeiten an Geräten, Gebäuden und Waffen. Du kannst die Aktionen wie in den _Fate Core
Grundregeln_ beschrieben einsetzen.

[.icon]#O# Du kannst Dinge reparieren, zerstören, unbrauchbar machen oder zusammenbauen, wenn Du die notwendige
Zeit und das passende Werkzeug dafür hast.

[.icon]#C# Du kannst die Fertigkeit einsetzen, um Vorteile durch die Modifikation von Gegenständen
zu erzielen, bspw. indem Du eine Kutsche verbesserst oder eine Waffe modifizierst. Du kannst auch Maschinen
sabotieren.

[.icon]#A# -

[.icon]#D# -

==== Heimlichkeit
_Heimlichkeit_ wird wie in den _Fate Core Grundregeln_ beschrieben verwendet.

==== Kämpfen
_Kämpfen_ wird wie in den _Fate Core Grundregeln_ für Nahkämpfe verwendet. Dabei werden sowohl bewaffnete als
auch unbewaffnete Nahkämpfe mit dieser Fertigkeit abgebildet. Für Fernkämpfe wird die Fertigkeit _<<Schießen>>_
eingesetzt.

[.icon]#O# Kämpfen wird in der Regel nicht für das Überwinden von _Hindernissen_ eingesetzt.

[.icon]#C# Mit Kämpfen kannst Du Vorteile erschaffen, in dem Du deinen Gegner zurückdrängst, ihn in eine
bestimmte Richtung treibst oder ihn entwaffnest. Du kannst auch einen Vorteil erschaffen, in dem Du einen
Gegner studierst und so eine Schwachstelle in seinem Kampfstil findest.

[.icon]#A# MISSING

[.icon]#D# Du kannst Dich mit Kämpfen MISSING

==== Kontakte
_Kontakte_ beschreibt Deine soziale Vernetzung. Mit dieser Fertigkeit kannst Du Informationen beschaffen,
Gegenstände kaufen oder verkaufen, auch auf dem Schwarzmarkt, oder Aufträge bekommen.

[.icon]#O# Du kannst die Fertigkeit einsetzen, um _Hindernisse_ durch die Unterstützung anderer zu lösen, in dem
du den passenden Händler für den Verkauf von heißer Ware findest oder jemanden auftreiben kannst, der Deine
zerstörte Rüstung wieder repariert.

[.icon]#C# Du kannst Vorteile erschaffen, wie bspw. einen Bekannten, der dir die richtigen Hintergrundinfos
beschafft oder einen eingeweihten, der dir den Ort eines Geheimverstecks erzählt.

[.icon]#A# -

[.icon]#D# Du kannst Dich gegen soziale Angriffe verteidigen, in dem Du Kontakte hast, die Deine Reputation
verbessern.

==== Kraft
_Kraft_ wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt. Dies gilt auch für die Sonderregel,
die Dir zusätzlich Kästchen für körperlichen Stress verschafft.

[#magie-fertigkeit]
==== Magie
*Neue Fertigkeit*

NOTE: Kann nur erworben werden, wenn Du das Extra _Magie_ hast. Siehe <<magie-kapitel>> für Details.

Mit dieser Fertigkeit kannst Du Zauber wirken, Magie erkennen und identifizieren, magische Gegenstände
herstellen usw.

[.icon]#O# Du kannst mittels Magie ein _Hindernis_ überwinden (bspw. eine verschlossene Tür öffnen).

[.icon]#C# Du kannst mittels Magie einen Vorteil erlangen (bspw. unsichtbar werden, größer wirken oder eine
Ablenkung in Form einer heranstürmenden Kreatur erzeugen).

[.icon]#A# Du kannst Kampfzauber verwenden, um andere Charakter in der physischen Welt anzugreifen.

[.icon]#D# Du kannst Gegenzauber verwenden um Dich gegen magische Angriffe in der physischen Welt zu
verteidigen.

==== Nachforschungen
Mit dieser Fertigkeit kannst Du Informationen über Dinge, Orte oder Situationen herausfinden, die bei
oberflächlicher Betrachtung nicht offentsichtlich sind. Dazu gehören bspw. das systematische Suchen nach
Geheimtüren, das Recherchen in lokalen Bibliotheken oder Archiven oder das Analysieren von Spuren an einem
Tatort.

[.icon]#O# Du kannst mittels Nachforschungen _Hindernisse_ in Form von schwer auffindbaren Informationen oder
versteckten Einrichtungen überwinden.

[.icon]#C# Du kannst Vorteile erzeugen, in dem Du Informationen über besonderes Verhalten oder Schwachstellen
herausfindest.

[.icon]#A# -

[.icon]#D# -

==== Provozieren
Du kannst _Provozieren_ wie in den Fate Core Grundregeln beschrieben einsetzen.

[.icon]#A# Du kannst Angriffe in der astralen Projektion durchführen.

==== Reiten
*Neue Fertigkeit*

Du kannst unterschiedliche Arten von Tieren nutzen, um Dich auf deren Rücken oder auch mit Hilfe von Kutschen
fortzubewegen. Dazu gehört das

* Reiten von Pferden
* Fahren von Kutschen und Ochsenkarren
* Fahren von Schlitten, die von Hunden gezogen werden
* Reiten auf einem Greif

und ähnliche Aktivitäten.

[.icon]#O# Du kannst lange Strecken oder schwierige Wege in kurzer Zeit überwinden.

[.icon]#C# Du kannst Aspekte erschaffen, die dir die Fortbewegung mit dem entsprechenden Tier vereinfachen.

[.icon]#A# Du kannst im berittenen Kampf dein Tier führen.

[.icon]#D# Du kannst dich im berittenen Kampf verteidigen, in dem Du ein Ausweichmanöver durchführst.

==== Ressourcen
NOTE: Kann nicht regulär erworben oder gesteigert werden. Siehe die Beschreibung unter <<Ressourcen>>.

Mit der Fertigkeit _Ressourcen_ kannst Du Dinge und Informationen kaufen, Leute bestechen und Du drückst
dadurch Deinen Lebensstil aus.

[.icon]#O# Du kannst _Ressourcen_ nutzen, um _Hindernisse_, die sich mit Geld aus der Welt schaffen lassen, zu
überwinden. Dazu gehört insbesondere das Bestechen von Personen oder das Kaufen von Gegenständen und
Informationen.

[.icon]#C# Du kannst _Ressourcen_ dazu nutzen, Personen Aspekte hinzuzufügen und kannst bewirken, dass sie Dir freundlich gestimmt
sind, wenn sie für Geld anfällig sind. Du kannst auch einen _Vorteil_ erschaffen, in dem Du einen _Aspekt_ für
einen Ausrüstungsgegenstand hinzufügst, der eine finanzielle Aufwertung darstellt.

[.icon]#A# -

[.icon]#D# -

==== Schießen
Du benutzt _Schießen_ um Deine Fernkampfwaffe einzusetzen. Überlicherweise tust Du dies beim _Angreifen_, aber
Du kannst es auch sehr gut verwenden, um Dir einen _Vorteil_ zu erschaffen (z.B. [.aspekt]#Sperrfeuer# oder
[.aspekt]#Feuerschutz#). In einigen Fällen kannst Du damit auch ein _Hindernis_ überwinden.

Unter Fernkampfwaffen fallen alle Bögen, Armbrüste, Schleudern, Blasrohre und auch alle Wurfwaffen, wie
Messer, Dolche, Speere, Äxte oder Bolas und Netze.

[.icon]#O# Schießen wird in der Regel nicht für das Überwinden genutzt. Du kannst es aber für
Schießwettbewerbe nutzen oder aber auch um einen unbeweglichen Gegenstand wie eine Vase zu zerstören.

[.icon]#C# Du kannst mit Schießen in einem Konflikt verschiedene Vorteile erschaffen, wie bspw.
[.aspekt]#Deckungsfeuer# oder [.aspekt]#festgenagelt#. Du kannst auch versuchen, Deine Gegner zu
[.aspekt]#entwaffnen#.

[.icon]#A# Natürlich kannst Du _Schießen_ einsetzen, um mit einer Fernkampfwaffe anzugreifen.

[.icon]#D# -

==== Täuschung
_Täuschung_ wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt.

==== Wahrnehmung
_Wahrnehmung_ wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt, bezieht sich dabei aber immer nur
auf die reale Welt.

==== Wille
_Wille_ wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt. Dies gilt insbesondere auch für die
_Sonderregel_, die dir zusätzliche _Stressfelder_ für _geistigen Stress_ bietet.

[.icon]#O# Denkaufgaben, Geduldsspiele oder Rätsel sind _Hindernisse_, die Du mit Wille überwinden kannst.

[.icon]#C# Du kannst Aspekte erzeugen wie [.aspekt]#konzentriert# oder [.aspekt]#fokussiert#.

[.icon]#A# -

[.icon]#D# Du nutzt Wille zur Verteidigung gegen geistige Angriffe.

==== Wissen
In Bezug auf die Aktionen wird _Wissen_ wie in den _Fate Core Grundregeln_ beschrieben eingesetzt.
