== Fertigkeiten
_Schwert & Schicksal_ nutzt die vollständige Liste der Fertigkeiten aus _Fate Core_. Einige der Fertigkeiten
werden modifiziert oder eingeschränkt. Es kommen einige wenige neue Fertigkeiten hinzu.

=== Übersicht
Die folgende Tabelle gibt einen Überblick über alle Fertigkeiten und welche Aktionen mit der jeweiligen
Fertigkeit möglich sind.

<<<

[frame=ends, grid=none, stripes=odd, cols="<2h,4*^1"]
|===
| Fertigkeit      | [.icon]#O# | [.icon]#C# | [.icon]#A# | [.icon]#D#

| Athletik        | X | X |   | X
| Charisma        | X | X |   | X
| Diebeskunst     | X | X |   |
| Empathie        | X | X |   | X
| Handwerk        | X | X |   |
| Heimlichkeit    | X | X |   | X
| Kämpfen         | X | X | X | X
| Kontakte        | X | X |   | X
| Kraft           | X | X |   | X
| Magie *         | X | X | X | X
| Nachforschungen | X | X |   |
| Provozieren     | X | X | X |
| Reiten          | X | X |   |
| Ressourcen *    | X | X | X | X
| Schießen        | X | X | X |
| Täuschung       | X | X |   | X
| Wahrnehmung     | X | X |   | X
| Wille           | X | X |   | X
| Wissen          | X | X |   | X
|===

NOTE: Fertigkeiten, hinter deren Namen ein Sternchen steht, können nur eingeschränkt erworben und
gesteigert werden. Details findest Du in der jeweiligen Beschreibung dieser Fertigkeiten.

=== Beschreibung der Fertigkeiten

==== Athletik
_Athletik_ wird so eingesetzt wie in den _Fate Core Grundregeln_ beschrieben.

[.icon]#O# Du kannst Hindernisse mittels körperlicher Bewegung überwinden: Schwimmen, Ausweichen, Rennen, ...

[.icon]#C# Du kannst einen Vorteil erschaffen, in dem Du auf eine höhere Position kletterst oder springst.

[.icon]#A# -

[.icon]#D# Du kannst _Athletik_ zur Verteidigung gegen alle Arten von Angriffen einsetzen (Nahkampf-
sowie Fernkampfangriffe).

===== Stunts
* Sprinter
* Kletterer
* Pfeile und Bolzen abwehren

==== Charisma
_Charisma_ wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt.

[.icon]#O# Du kannst andere Personen inspirieren oder überzeugen.

[.icon]#C# Du kannst andere dazu bringen, dir zu vertrauen oder dir zu folgen.

[.icon]#A# -

[.icon]#D# Du kannst dich gegen Angriffe verteidigen, die deinen Ruf schädigen.

===== Stunts
* Einen guten Eindruck machen
* Demagoge
* beliebt

==== Diebeskunst
Mit _Diebeskunst_ kannst Du Gegenstände stehlen, Spuren verwischen, Objekte am Körper verbergen, an Orte gelangen,
zu denen Dir der Zutritt eigentlich verwehrt ist und Ähnliches.

[.icon]#O# Du kannst Taschendiebstahl, eine einfache Infiltration durchführen oder deine Spuren verwischen.
Du kannst Schlösser knacken und Fallen überwinden.

[.icon]#C# Du kannst Orte oder Personen ausspionieren und dabei Schwachstellen für einen Einbruch oder
Diebstahl aufdecken.

[.icon]#A# -

[.icon]#D# -

===== Stunts
* Meisterdieb
* Entfesslungskünstler
* Es gibt immer einen Ausweg

==== Empathie
Mit _Empathie_ kannst Du Gefühle und Regungen in Personen, Monstern und Tieren wahrnehmen.

[.icon]#O# -

[.icon]#C# Du kannst den emotionalen Zustand deines Gegenübers erkennen und darüber neue Aspekte erschaffen.

[.icon]#A# -

[.icon]#D# Du kannst Dich mit Empathie gegen Angriffe wie _Täuschung_ verteidigen und Lügen anderer durchschauen.

===== Stunts
* Lügendetektor
* Therapeut

===== Sonderregel
Du kannst _Empathie_ nutzen um anderen zu helfen, sich von geistigen Konsequenzen zu erholen. Dazu erschaffst Du einen
Vorteil, dessen _freier Einsatz_ Du weitergibst. Mit dem Stunt _Therapeut_ wird dieser Einsatz verbessert.

==== Handwerk
Umfasst alle Arten von Arbeiten an Geräten, Gebäuden, Waffen und Rüstungen. Du kannst die Aktionen wie in den _Fate Core
Grundregeln_ beschrieben einsetzen.

[.icon]#O# Du kannst Dinge reparieren, zerstören, unbrauchbar machen oder zusammenbauen, wenn Du die notwendige
Zeit und das passende Werkzeug dafür hast.

[.icon]#C# Du kannst die Fertigkeit einsetzen, um Vorteile durch die Modifikation von Gegenständen
zu erzielen, bspw. indem Du eine Kutsche verbesserst oder eine Waffe modifizierst. Du kannst auch Maschinen
sabotieren.

[.icon]#A# -

[.icon]#D# -

===== Stunts
* Waffenschmied
* Rüstungsmacher

==== Heimlichkeit
_Heimlichkeit_ wird wie in den _Fate Core Grundregeln_ beschrieben verwendet.

[.icon]#O# Du kannst dich heimlich an Orte bewegen, an denen Du nicht sein solltest oder anderen Personen einen Gegenstand
zuspielen. Die Probe kann passiven Widerstand haben oder gegen die aktive <<Wahrnehmung>> Deines Gegenüber ausgeführt werden.

[.icon]#C# Du kannst Dich oder dein Lager verstecken.

[.icon]#A# -

[.icon]#V# -

==== Kämpfen
_Kämpfen_ wird wie in den _Fate Core Grundregeln_ für Nahkämpfe verwendet. Dabei werden sowohl bewaffnete als
auch unbewaffnete Nahkämpfe mit dieser Fertigkeit abgebildet. Für Fernkämpfe wird die Fertigkeit _<<Schießen>>_
eingesetzt.

[.icon]#O# Kämpfen wird in der Regel nicht für das Überwinden von Hindernissen eingesetzt.

[.icon]#C# Mit Kämpfen kannst Du Vorteile erschaffen, in dem Du deinen Gegner zurückdrängst, ihn in eine
bestimmte Richtung treibst oder ihn entwaffnest. Du kannst auch einen Vorteil erschaffen, in dem Du einen
Gegner studierst und so eine Schwachstelle in seinem Kampfstil findest.

[.icon]#A# Selbstverständlich kannst Du mit _Kämpfen_ angreifen.

[.icon]#D# Du kannst Dich mit Kämpfen gegen Nahkampfangriffe verteidigen. Das Verteidigen gegen einen
bewaffneten Angriff setzt voraus, dass Du eine entsprechende Waffe führst (Du kannst Dich nicht kämpfend mit
bloßen Händen gegen einen Schwertangriff verteidigen - dafür nutzt Du <<Athletik>>). SL: Du hast das letzte
Wort darüber, ob eine Verteidigung mit _Kämpfen_ zulässig ist oder nicht.

===== Stunts
* Waffenmeister
* Niederschlagen
* Rundumschlag
* Hinterhältiger Angriff
* Entwaffnender Schlag

==== Kontakte
_Kontakte_ beschreibt Deine soziale Vernetzung. Mit dieser Fertigkeit kannst Du Informationen beschaffen,
Gegenstände kaufen oder verkaufen, auch auf dem Schwarzmarkt, oder Aufträge bekommen.

[.icon]#O# Du kannst die Fertigkeit einsetzen, um Hindernisse durch die Unterstützung anderer zu lösen, in dem
du den passenden Händler für den Verkauf von heißer Ware findest oder jemanden auftreiben kannst, der Deine
zerstörte Rüstung wieder repariert.

[.icon]#C# Du kannst Vorteile erschaffen, wie bspw. einen Bekannten, der dir die richtigen
Hintergrundinformationen beschafft oder einen eingeweihten, der dir den Ort eines Geheimverstecks erzählt.

[.icon]#A# -

[.icon]#D# Du kannst Dich gegen soziale Angriffe verteidigen, in dem Du Kontakte hast, die Deine Reputation
verbessern.

===== Stunts
* Ein Freund in jeder Stadt

==== Kraft
_Kraft_ wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt.

[.icon]#O# Du kannst verklemmte Türen öffnen, Dinge hochheben oder Einrichtungen mit bloßer Kraft zerstören.
Du kannst _Kraft_ in einem Wettbewerb wie bsp. Armdrücken einsetzen.

[.icon]#C# Du kannst Hindernisse in den Weg stellen, die deine Verfolger aufhalten oder verlangsamen. Du
kannst eine Kutsche anheben, sodass ein anderer Charakter das defekte Wagenrad einfacher reparieren kann.

[.icon]#A# -

[.icon]#V# Du kannst Dich in einer Schlägerei mittels Kraft verteidigen.

===== Sonderregel

Mit hohen Werten in Kraft erhältst du zusätzliche Felder für körperlichen Stress. Siehe <<Stress>> für weitere
Informationen.

===== Stunts
* Gewichtheber

[#magie-fertigkeit]
==== Magie
*Neue Fertigkeit*

NOTE: Kann nur erworben werden, wenn Du das Extra _Magie_ hast. Siehe <<magie-kapitel>> für Details.

Mit dieser Fertigkeit kannst Du Zauber wirken, Magie erkennen und identifizieren, magische Gegenstände
herstellen usw.

[.icon]#O# Du kannst mittels Magie ein Hindernis überwinden (bspw. eine verschlossene Tür öffnen), in dem
du einen entsprechenden Zauber wirkst.

[.icon]#C# Du kannst mittels Magie einen Vorteil erlangen (bspw. unsichtbar werden, größer wirken oder eine
Ablenkung in Form einer heranstürmenden Kreatur erzeugen). Du kannst auch Magie entdecken und damit einen
Aspekt aufdecken.

[.icon]#A# Du kannst Kampfzauber verwenden, um andere Charakter anzugreifen.

[.icon]#D# Du kannst Gegenzauber verwenden um Dich gegen magische Angriffe zu verteidigen.

===== Stunts
Jeder Zauber wird als Stunt behandelt. Siehe <<magie-kapitel>> für weitere Informationen.

==== Nachforschungen
Mit dieser Fertigkeit kannst Du Informationen über Dinge, Orte oder Situationen herausfinden, die bei
oberflächlicher Betrachtung nicht offensichtlich sind. Dazu gehören bspw. das systematische Suchen nach
Geheimtüren, das Recherchen in lokalen Bibliotheken oder Archiven oder das Analysieren von Spuren an einem
Tatort.

[.icon]#O# Du kannst mittels Nachforschungen Hindernisse in Form von schwer auffindbaren Informationen oder
versteckten Einrichtungen überwinden.

[.icon]#C# Du kannst Vorteile erzeugen, in dem Du Informationen über besonderes Verhalten oder Schwachstellen
herausfindest. Du kannst Spuren lesen und dadurch Aspekte erzeugen, die dir die Richtung, die Art der Wesen
usw. hinter einer Spur aufzeigen.

[.icon]#A# -

[.icon]#D# -

===== Stunts
* Fährtenleser

==== Provozieren
Du kannst _Provozieren_ wie in den _Fate Core Grundregeln_ beschrieben einsetzen.

[.icon]#O# Du kannst an einem Türsteher vorbeikommen, in dem Du ihn provozierst, sodass er seinen Posten
aufgibt.

[.icon]#C# Du kannst andere provozieren und dadurch einen Vorteil erlangen, in dem Du sie ablenkst oder sie
die Beherrschung verlieren lässt.

[.icon]#A# Du kannst andere Charaktere mental angreifen, in dem Du sie zu Aktionen provozierst, die sie die
Beherrschung verlieren lassen.

[.icon]#D# -

==== Reiten
*Neue Fertigkeit*

Du kannst unterschiedliche Arten von Tieren nutzen, um Dich auf deren Rücken oder auch mit Hilfe von Kutschen
fortzubewegen. Dazu gehört das

* Reiten von Pferden
* Fahren von Kutschen und Ochsenkarren
* Fahren von Schlitten, die von Hunden gezogen werden
* Reiten auf einem Greif

und ähnliche Aktivitäten.

Für das "normale" Reiten ohne Zeitdruck auf angemessenem Terrain ist keine Probe auf diese Fertigkeit
erforderlich. Wenn du aber besonders schnell oder durch gefährliches Terrain unterwegs bist, kann dies als
Hindernis gelten. SL: Du entscheidest, wann eine Probe notwendig ist.

[.icon]#O# Du kannst lange Strecken oder schwierige Wege in kurzer Zeit überwinden.

[.icon]#C# Du kannst Aspekte erschaffen, die dir die Fortbewegung mit dem entsprechenden Tier vereinfachen.

[.icon]#A# -

[.icon]#D# -

===== Stunts
* vertrautes Reittier

==== Ressourcen
NOTE: Kann nicht regulär erworben oder gesteigert werden. Siehe die Beschreibung unter <<Ressourcen>>.

Mit der Fertigkeit _Ressourcen_ kannst Du Dinge und Informationen kaufen, Leute bestechen und Du drückst
dadurch Deinen Lebensstil aus.

[.icon]#O# Du kannst Ressourcen nutzen, um Hindernisse, die sich mit Geld aus der Welt schaffen lassen, zu
überwinden. Dazu gehört insbesondere das Bestechen von Personen oder das Kaufen von Gegenständen und
Informationen.

[.icon]#C# Du kannst Ressourcen dazu nutzen, Personen Aspekte hinzuzufügen und kannst bewirken, dass sie Dir
freundlich gestimmt sind, wenn sie für Geld anfällig sind. Du kannst auch einen Vorteil erschaffen, in dem Du
einen Aspekt für einen Ausrüstungsgegenstand hinzufügst, der eine finanzielle Aufwertung darstellt.

[.icon]#A# -

[.icon]#D# -

===== Stunts
Für die Fertigkeit Ressourcen kannst du _keine_ Stunts erwerben.

==== Schießen
Du benutzt _Schießen_ um Deine Fernkampfwaffe einzusetzen. Überlicherweise tust Du dies beim _Angreifen_, aber
Du kannst es auch sehr gut verwenden, um Dir einen Vorteil zu erschaffen (z.B. [.aspekt]#Sperrfeuer# oder
[.aspekt]#Feuerschutz#). In einigen Fällen kannst Du damit auch ein _Hindernis_ überwinden.

Unter Fernkampfwaffen fallen alle Bögen, Armbrüste, Schleudern, Blasrohre und auch alle Wurfwaffen, wie
Messer, Dolche, Speere, Äxte oder Bolas und Netze.

[.icon]#O# Schießen wird in der Regel nicht für das Überwinden genutzt. Du kannst es aber für
Schießwettbewerbe nutzen oder aber auch um einen unbeweglichen Gegenstand wie eine Vase zu zerstören.

[.icon]#C# Du kannst mit Schießen in einem Konflikt verschiedene Vorteile erschaffen, wie bspw.
[.aspekt]#Deckungsfeuer# oder [.aspekt]#festgenagelt#. Du kannst auch versuchen, Deine Gegner zu
[.aspekt]#entwaffnen#.

[.icon]#A# Natürlich kannst Du Schießen einsetzen, um mit einer Fernkampfwaffe anzugreifen.

[.icon]#D# -

===== Stunts
* Scharfschütze
* Waffenmeister
* Hinterhältiger Angriff

==== Täuschung
_Täuschung_ wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt.

Mit _Täuschung_ kannst du andere Charaktere über deine Motive im Unklaren lassen oder gezielt täuschen.

[.icon]#O# Du kannst mittels Täuschung ein Hindernis überwinden, in dem Du bspw. einem Türsteher eine falsche
Geschichte auftischst.

[.icon]#C# Du kannst Dir einen Vorteil verschaffen, in dem Du Lügengeschichten verbreitest, die Dir einen Vorteil
gewähren.

[.icon]#A# -

[.icon]#D# Du kannst Dich mit _Täuschung_ verteidigen, falls jemand versucht, mittles _Nachforschungen_ etwas über Dich
herauszufinden.

===== Stunts
* Lügen über Lügen
* Gedankenspiele

==== Wahrnehmung
_Wahrnehmung_ wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt.

Du nutzt Wahrnehmung um Personen und Gegenstände um Dich herum wahrzunehmen. Wahrnehmung erfasst die Situation im allgemeinen;
für einen Blick für die Details nutzt Du _Nachforschungen_.

[.icon]#O# In der Regel nutzt Du _Wahrnehmung_ nicht um Hindernisse zu überwinden, da es eine passive Fertigkeit ist.

[.icon]#C# Du kannst Dinge hören oder sehen die Dir einen Vorteil gewähren, in dem dadurch ein Aspekt offenbart wird.

[.icon]#A# -

[.icon]#V# Du kannst Dich gegen Angriffe mit _Heimlichkeit_ verteidigen.

===== Stunts
* Gefahreninstinkt

==== Wille
_Wille_ wird wie in den _Fate Core Grundregeln_ beschrieben eingesetzt. Dies gilt insbesondere auch für die
Sonderregel, die dir zusätzliche Stressfelder für geistigen Stress bietet.

[.icon]#O# Denkaufgaben, Geduldsspiele oder Rätsel sind Hindernisse, die Du mit Wille überwinden kannst.

[.icon]#C# Du kannst Aspekte erzeugen wie [.aspekt]#konzentriert# oder [.aspekt]#fokussiert#.

[.icon]#A# -

[.icon]#D# Du nutzt Wille zur Verteidigung gegen geistige Angriffe.

===== Sonderregel

Mit hohen Werten in Wille erhältst Du zusätzliche Felder für geistigen Stress. Siehe <<Stress>> für weitere Informationen.

===== Stunts
* Stärke durch Entschlossenheit
* abgebrüht

==== Wissen
In Bezug auf die Aktionen wird _Wissen_ wie in den _Fate Core Grundregeln_ beschrieben eingesetzt.

[.icon]#O# Du nutzt Wissen, um Probleme zu lösen, die mit erlerntem Wissen gelöst werden können. Dazu gehört bspw.
das Übersetzen einer alten Sprache oder auch das Finden von Büchern in einer alten Bibliothek.

[.icon]#C# Du kannst mit Wissen Aspekte erzeugen, die Dein Wissen über bestimmte Monster oder andere Gegner darstellen.

[.icon]#A# -

[.icon]#D# -

===== Stunts
* Davon hab ich gelesen
