== Ressourcen

Ressourcen werden eingesetzt, um Dinge zu kaufen sowie Lebensstil und Status auszudrücken. Damit die Spieler 
nicht jede einzelne Goldmünze ihrer Charaktere buchhalterisch erfassen müssen, verwendet _Schwert & Schicksal_
ein einfacheres System basierend auf der Fertigkeit _Ressourcen_ aus den Grundregeln von _Fate Core_.

Abweichend zu den Grundregeln kann diese Fertigkeit jedoch nicht erworben werden und wird auch nicht in der 
Fertigkeitenpyramide oder zur Säulenbildung mit herangezogen. Diese Fertigkeit wird durch die Spielleitung 
gesteuert und zu _Meilensteinen_ modifiziert. Dabei sind auch größere Sprünge möglich.

Die Spieler können diese Fertigkeit wie in den Grundregeln beschrieben einsetzen um Ausrüstungen zu kaufen 
oder Kontakte zu bestechen usw. Übliche Aktivitäten, wie das Bezahlen einer Übernachtung im Wirtshaus oder 
einer Mahlzeit sollten kein Hindernis darstellen und folglich keine Probe erfordern. Wenn die Charaktere aber 
im "besten Gasthaus der ganzen nördlichen Gebiete" in der "Königssuite" nächtigen wollen, kann das schon ein 
Hindernis mit "gutem passiven Widerstand" darstellen, dass die Charaktere mittels _Ressourcen_ überwinden 
müssen (oder sie finden einen anderen Weg in die Suite).

SL: Du entscheidest, wie "knapp bei Kasse" die Charaktere sind und was erforderlich ist, damit die Fertigkeit
_Ressourcen_ verbessert oder verschlechtert wird. Die Änderung sollte zu einem _Meilenstein_ erfolgen, aber
natürlich kann es hier auch Ausnahmen geben.
