== Waffen, Rüstungen und sonstige Ausrüstung

[sidebar]
****
Waffen und Ausrüstungen folgen den _Extras_-Regeln aus dem _Fate Core Grundregelbuch_ ab S.285. Sie
verfügen über eine Waffen- bzw. Rüstungsstufe, die zusätzliche Erfolgsstufen generieren bzw.
egalisieren.
****

Waffen liefern zusätzliche Trefferstufen bei einem Erfolg, Rüstungen "verschlucken" Trefferstufen bei
einem Treffer. Es gibt vier Stufen für Waffen und Rüstungen.

Wichtig ist dabei, dass diese Trefferstufen erst zum Tragen kommen, wenn ein Treffer erfolgt ist. Das bedeutet,
dass der angreifende Charakter das Ziel zunächst treffen muss, bevor der zusätzliche Schaden der Waffe zum
Tragen kommt.

<<<

=== Waffen und Rüstungen

In der folgenden Tabelle findest du eine Übersicht über verschiedene Waffen und Rüstungen sowie ihre Stufen.
Diese Tabelle sollte nicht als vollständig angesehen werden; wenn ihr weitere Waffen oder Rüstungen aufnehmen
wollt, dann ergänzt sie einfach und sortiert sie "passend" ein.

[frame=ends, grid=none, stripes=even, cols="^1,3*<4a"]
|===
| Stufe | Nahkampfwaffen | Fernkampfwaffen | Rüstungen

| 0
|
* Faustkampf
* Ringkampf
|
* Netz
* Bola
|
* nackte Haut
* Alltagskleidung

| 1
|
* Messer
* Dolch
* Knüppel
|
* Blasrohr
* Schleuder
* Wurfmesser
|
_Leichte Rüstungungen_

* Waffenrock
* Lederrüstung
* beschlagenes Leder
* Kettenhemd

| 2
|
* Morgenstern
* Schwert
* Speer
* Streitaxt
* Streitkolben
* Streithammer

|
* Bogen
* Handarmbrust
* leichte Armbrust
* Wurfaxt
* Wurfspeer
|
_Mittelschwere Rüstungen_

* Schuppenpanzer
* Kettenpanzer
* Brustplatte

| 3
|
* Hellebarde
* Zweihänder
|
* schwere Armbrust
|
* Schienenpanzer
* Bänderpanzer
* Plattenpanzer
| 4
|
|
|
* Ritterrüstung
|===

==== Schilde und Helme

Schilde und Helme gewähren keinen Bonus auf die Rüstungsstufe; sie egalisieren daher keine Trefferstufen.
Stattdessen fungieren sie wie Aspekte, die - eine entsprechende Situation vorausgesetzt - eingesetzt werden
können, um eine Probe auf Verteidigen zu verbessern. Der Einsatz kostet wie üblich einen Fate Punkt.

SL: Du entscheidest letzten Endes, ob der Einsatz gerechtfertigt ist oder nicht. Ein auf dem Rücken getragenes
Schild wird in der Regel keinen Einsatz als Aspekt rechtfertigen - möglicherweise jedoch, wenn der Angriff
mit einer Fernkampfwaffe von hinten erfolgt. Helm und Schild können auch zum Reizen eingesetzt werden, bspw.
bei Proben auf Klettern oder Schwimmen.

==== Reichweiten

Es gibt keine pauschalen Reichweitenbegrenzungen für Waffen. Stattdessen solltet ihr gemeinsam überlegen,
welche Gegner von einer Waffe noch erreicht werden können. Verwendet Aspekte wie [.aspekt]#sehr weit
entfernt# mit freien Einsätzen für die Verteidigung um entsprechende Situationen aufzulösen.

==== Munition und Nachladen

Wir gehen davon aus, dass die erfahrenen Abenteuer auf ihre Ausrüstung achten und dazu gehört auch das 
Beschaffen oder Herstellen von Munition wie Pfeile oder Bolzen. Auch das Nachladen einer Waffe sollte von
einem kundigen Abenteurer problemlos erledigt werden können. Falls eine Waffe einen aufwändigen 
Nachlademechnismus hat könnt ihr einen Aspekt wie [.aspekt]#leergeschossen# verwenden um auszudrücken, dass
die Waffe nicht abgefeuert werden kann, bis der Aspekt entfernt wurde (bspw. durch das Nachladen).

Sollten die Charaktere in eine Situation kommen, in der sie nur über sehr eingeschränkte Munitionsreserven
verfügen, könnt ihr einen Aspekt wie zum Beispiel [.aspekt]#wenig Munition# festlegen. SL: Du kannst diesen
Aspekt reizen, um auszudrücken, dass die Abenteuer keine Munition mehr haben. Der Aspekt wird dann entfernt
sobald die Charaktere wieder Zugriff auf Munitionsreserven haben.

=== Weitere Ausrüstung

Wir gehen davon aus, dass die Charaktere erfahrene Abenteurer sind, die das nötige Handwerkszeug mitbringen,
um in der Welt von _Schwert & Schicksal_ zu überleben. Wenn die Charaktere eine Laterne, ein Seil oder eine
Tasche benötigen, dann sollten sie sie einfach dabei haben. Gilt das nicht, sollte die SL vorher einen
entsprechenden Aspekt festlegen - wie bspw. [.aspekt]#nur die nackte Haut# - so dass alle wissen, dass
Ausrüstung zur Zeit rar ist. Dies gilt auch für die notwendigen Zaubermaterialien eines Magiers.

Besondere Ausrüstungsgegenstände, wie bspw. das "Herz eines jungen roten Drachen" oder "100 Fingernägel von
Ogern der südlichen Sümpfe" sind von dieser Regel natürlich ausgenommen. Die SL hat immer das letzte Wort,
ob ein Gegenstand "üblich" oder eher nicht ist.
