== Charakteraspekte

Bei der Erschaffung eines Charakters für _Fate Core_ legt der Spieler zunächst *Konzept* und *Dilemma* des
Charakters fest. Dies gilt auch für _Schwert & Schicksal_. Danach kannst Du noch drei weitere Aspekte
wählen. 

=== Rassen

Die Rasse des Charakters in einer high-Fantasy-Welt ist durchaus wichtig und beschert dem Charakter Vorteile
sowie auch Komplikationen. Rassen werden als _Extra_ realisiert. Jedoch muss der Charakter die Rasse in seinem
Konzept benennen; diese kann sich auch während des Spiels nicht ändern.

=== Nutzung von Magie

_Schwert & Schicksal_ kennt zwei Arten von Magie: arkane und göttliche. Die göttliche Magie wird einem 
Charakter durch ein höheres Wesen gewährt, während die arkane Magie eine angeborene Kraft darstellt. 
Regeltechnisch werden beide Arten in weiten Teilen gleich behandelt. Sie werden über ein _Extra_ realisiert.

Da arkane Fähigkeiten jedoch angeboren sind müssen diese im Konzept des Charakters benannt werden. Dabei 
spielt es keine Rolle, welche Begriffe (wie bspw. _Magier_, _Hexenmeister_, _Schamane_, _Adept_, ...) genannt
werden solange alle Spieler das gleiche Verständnis davon haben, dass diese Charakter über arkane Fähigkeiten
verfügt.