name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rules:
    name: Generate HTML rules from Asciidoc sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true      
 
      - uses: reitzig/actions-asciidoctor@v2.0.0
        with:
          version: 2.0.15

      - run: asciidoctor -a stylesheet=./regeln/styles/html.css ./regeln/doc/SchwertUndSchicksal.adoc
      
